### ISSUE TITLE
Error: "Stage0: X-GPGAuth-Verify-Response should be set"

### ISSUE THREAD

**Issue by colinfrei** [liip/python-gpgauth-cli#7]
When trying to search with wrench I get an error that X-GPGAuth-Verify-Response should be set.

Here's the full error:
```Colins-MBP:~ colin$ wrench search foo
Stage0: X-GPGAuth-Verify-Response should be set
Traceback (most recent call last):
  File "/Users/colin/.local/bin/wrench", line 11, in <module>
    sys.exit(main())
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/wrench/commands.py", line 257, in main
    cli(obj={})
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/wrench/commands.py", line 171, in search
    session = create_session_from_context(ctx.obj)
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/wrench/commands.py", line 72, in create_session_from_context
    session.authenticate()
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/requests_gpgauthlib/gpgauth_session.py", line 216, in authenticate
    return self.is_authenticated_with_token
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/requests_gpgauthlib/gpgauth_session.py", line 200, in is_authenticated_with_token
    user_token_result=self.user_auth_token
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/requests_gpgauthlib/gpgauth_session.py", line 157, in user_auth_token
    if not self.server_identity_is_verified:
  File "/Users/colin/.local/venvs/passbolt-wrench/lib/python3.6/site-packages/requests_gpgauthlib/gpgauth_session.py", line 141, in server_identity_is_verified
    raise GPGAuthStage0Exception("Verify endpoint wrongly formatted")
requests_gpgauthlib.exceptions.GPGAuthStage0Exception: Verify endpoint wrongly formatted
```

**Comment by sephii** [comment]
This is related to https://github.com/liip/requests_gpgauthlib/issues/8, thanks for reporting. :)
